# This is a config for E2B sandbox template.
# You can use template ID (jchizu9pbc62lu46os5m) or template name (vibe-nextjs-test-maaz1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-maaz1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-maaz1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-maaz1')

team_id = "38c57808-285e-4118-b5fd-54d636f5bed3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-maaz1"
template_id = "jchizu9pbc62lu46os5m"
